apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecotech-server-ingress
  labels:
    name: ecotech-server-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ecotech-server
                port:
                  number: 8000